const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, AlignmentType, HeadingLevel } = require('docx');
const analyticsService = require('./analyticsService');
const predictionService = require('./predictionService');
const Employee = require('../../models/Employee');

class AIReportGenerator {
  /**
   * Generate PDF Report for an Employee
   */
  async generateEmployeePDF(employeeId, res) {
    const employee = await Employee.findById(employeeId);
    const analytics = await analyticsService.getEmployeeDeepAnalytics(employeeId);
    
    if (!employee || !analytics) throw new Error("Employee or Analytics not found");

    const doc = new PDFDocument({ margin: 50 });
    
    // Header
    doc.fillColor("#444444").fontSize(20).text("Employee Analytics Report", { align: "center" });
    doc.moveDown();
    doc.strokeColor("#aaaaaa").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Employee Details
    doc.fillColor("#000000").fontSize(14).text(`Name: ${employee.name}`);
    doc.text(`Department: ${employee.role}`);
    doc.text(`ID: ${employee.employeeId || employee._id}`);
    doc.moveDown();

    // Analytics Section
    doc.fontSize(16).fillColor("#2c3e50").text("Attendance Performance Summary", { underline: true });
    doc.moveDown(0.5);
    
    const stats = [
      ["Attendance Rate", `${analytics.attendancePercentage}%`],
      ["Punctuality Score", `${analytics.punctualityScore}/100`],
      ["Consistency Score", `${analytics.consistencyScore}/100`],
      ["Work Reliability", `${analytics.reliabilityScore}/100`],
      ["Overall Performance", analytics.status]
    ];

    stats.forEach(([label, value]) => {
      doc.fontSize(12).fillColor("#333333").text(`${label}: `, { continued: true }).fillColor("#000000").text(value);
    });

    doc.moveDown();

    // AI Insights (Mocked logic for now, could call Gemini)
    doc.fontSize(16).fillColor("#2c3e50").text("AI Generated Insights", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor("#444444").text(
      `Based on the analysis, ${employee.name} shows ${analytics.status.toLowerCase()} performance. ` +
      `The attendance rate of ${analytics.attendancePercentage}% indicates ${parseFloat(analytics.attendancePercentage) > 90 ? "exceptional" : "steady"} commitment. ` +
      `Recommendation: ${parseFloat(analytics.punctualityScore) < 70 ? "Address frequent late arrivals." : "Maintain current punctuality standards."}`
    );

    doc.moveDown(2);
    doc.fontSize(10).fillColor("#aaaaaa").text("Generated by Advanced AI Analytics Engine", { align: "center" });

    doc.pipe(res);
    doc.end();
  }

  /**
   * Generate DOCX Report
   */
  async generateEmployeeDOCX(employeeId) {
    const employee = await Employee.findById(employeeId);
    const analytics = await analyticsService.getEmployeeDeepAnalytics(employeeId);

    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            text: "Employee Analytics Report",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({
            children: [
              new TextRun({ text: `Name: ${employee.name}`, bold: true }),
              new TextRun({ text: `\nDepartment: ${employee.role}`, break: 1 }),
              new TextRun({ text: `\nReport Date: ${new Date().toLocaleDateString()}`, break: 1 }),
            ],
          }),
          new Paragraph({ text: "" }),
          new Paragraph({ text: "Performance Metrics", heading: HeadingLevel.HEADING_2 }),
          new Table({
            rows: [
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Metric")] }),
                  new TableCell({ children: [new Paragraph("Value")] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Attendance Rate")] }),
                  new TableCell({ children: [new Paragraph(`${analytics.attendancePercentage}%`)] }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph("Overall Score")] }),
                  new TableCell({ children: [new Paragraph(`${analytics.overallScore}/100`)] }),
                ],
              }),
            ],
          }),
        ],
      }],
    });

    return await Packer.toBuffer(doc);
  }


  /**
   * Generate System-Wide Intelligence Report PDF
   */
  async generateIntelligenceReportPDF(res) {
    const data = await analyticsService.getGeneralInsights();
    const predictions = await predictionService.getAbsencePredictions();
    
    const doc = new PDFDocument({ margin: 50 });
    
    // Header with Branding
    doc.fillColor("#1e1b4b").rect(0, 0, 612, 80).fill(); // Indigo dark header
    doc.fillColor("#ffffff").fontSize(22).text("Workforce Intelligence Executive Report", 50, 30);
    doc.fontSize(10).text(`Generated by Advanced AI Engine • ${new Date().toLocaleString()}`, 50, 55);
    
    doc.moveDown(4);

    // Executive Summary Section
    doc.fillColor("#1e293b").fontSize(18).text("1. Executive Summary", { underline: true });
    doc.moveDown(0.5);
    doc.fillColor("#475569").fontSize(12).text(
      "This report provides a multi-dimensional analysis of workforce attendance, behavioral patterns, and performance rankings. " +
      "The data has been processed using neural predictive models to identify operational risks and elite performers."
    );
    doc.moveDown();

    // 2. Department Performance
    doc.fillColor("#1e293b").fontSize(16).text("2. Departmental Performance Matrix");
    doc.moveDown(0.5);
    
    data.rawStats.departmentStats.forEach(dept => {
      doc.fontSize(11).fillColor("#334155")
         .text(`${dept.department}: `, { continued: true })
         .fillColor("#4f46e5").text(`${dept.avgAttendance}% Avg. Attendance`, { continued: true })
         .fillColor("#64748b").text(` (${dept.totalEmployees} employees)`);
    });
    doc.moveDown();

    // 3. Critical Anomalies
    doc.fillColor("#1e293b").fontSize(16).text("3. Behavioral Anomaly Detection");
    doc.moveDown(0.5);
    
    if (data.rawStats.anomalies.length > 0) {
      data.rawStats.anomalies.slice(0, 10).forEach(anomaly => {
        doc.fontSize(10).fillColor("#e11d48").text(`[${anomaly.severity}] `, { continued: true })
           .fillColor("#334155").text(`${anomaly.name} - ${anomaly.type}: `, { continued: true })
           .fillColor("#64748b").text(anomaly.description);
      });
    } else {
      doc.fontSize(11).fillColor("#64748b").text("No significant behavioral anomalies detected in the current cycle.");
    }
    doc.moveDown();

    // 4. Absence Risk Predictions
    doc.fillColor("#1e293b").fontSize(16).text("4. Predictive Absence Risk Scan");
    doc.moveDown(0.5);
    
    const criticalRisks = predictions.filter(p => p.status === 'Critical');
    if (criticalRisks.length > 0) {
      doc.fillColor("#e11d48").fontSize(11).text(`ALERT: ${criticalRisks.length} employees identified at CRITICAL risk of absenteeism.`);
      criticalRisks.forEach(risk => {
        doc.fontSize(10).fillColor("#334155").text(`- ${risk.name}: ${risk.reason}`);
      });
    } else {
      doc.fillColor("#059669").fontSize(11).text("Predictive analysis indicates stable workforce attendance for the upcoming period.");
    }

    doc.moveDown(2);
    doc.strokeColor("#e2e8f0").lineWidth(0.5).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();
    doc.fillColor("#94a3b8").fontSize(10).text("End of Intelligence Report. All data is synchronized in real-time with the central database.", { align: "center" });

    doc.pipe(res);
    doc.end();
  }
}

module.exports = new AIReportGenerator();
